Add guide for saving .chor files
SleipnirGroup/Choreo pull request #1004
Opened 2024-12-11 15:00 UTC by Daniel1464

Now, users must save their .chor files in deploy/choreo; this guide makes sure to tell them that

2024-12-11 22:50 UTC, katzuv commented on docs/document-settings/saving-trajectories.md
> +    Not doing so will result in ChoreoLib(and PathPlannerLib) being unable to parse your project.
```suggestion
    Not doing so will result in ChoreoLib (and PathPlannerLib) being unable to parse your project.
```

2024-12-11 22:50 UTC, katzuv commented on docs/document-settings/saving-trajectories.md
> +Once trajectories are created by choreo, they must be saved within your robot project.
```suggestion
Once trajectories are created by Choreo, they must be saved within your robot project.
```

2024-12-11 22:50 UTC, katzuv commented on docs/document-settings/saving-trajectories.md
> +Once a .chor file is saved to a directory(folder), saving your project will
```suggestion
Once a .chor file is saved to a directory (folder), saving your project will
```

2024-12-16 19:16 UTC, oh-yes-0-fps commented
telling them to name their `.chor` file `Choreo.chor` is silly, do `{project_name}.chor` or smthn

2024-12-16 21:15 UTC, Daniel1464 commented
> This is not accurate for Python projects

where does choreolib/pplib read for those

2024-12-16 21:17 UTC, shueja commented
> where does choreolib/pplib read for those

Currently it reads from project root. There was discussion today about making that user-settable.

2024-12-17 01:12 UTC, shueja requested changes
Be more mindful of capitalization and code block usage.

2024-12-17 01:12 UTC, shueja commented on docs/usage/saving.md
> +2. Open the choreo sidebar and click "save project"(see "Sidebar Navigation" for more details).
```suggestion
2. Open the Choreo sidebar and click "Save Project"(see "Sidebar Navigation" for more details).
```

2024-12-17 01:12 UTC, shueja commented on docs/usage/saving.md
> +1. Open the choreo sidebar and click "save project"(see "Sidebar Navigation" for more details).
```suggestion
1. Open the Choreo sidebar and click "Save Project"(see "Sidebar Navigation" for more details).
```

2024-12-17 01:12 UTC, shueja commented on docs/usage/saving.md
> +This opens the system’s file save dialog to select where to save the robot’s `.chor` file. Choreo strongly recommends saving this file in your deploy/choreo folder within your project.
```suggestion
This opens the system’s file save dialog to select where to save the robot’s `.chor` file. Choreo strongly recommends saving this file in your `deploy/choreo` folder within your project.
```

2024-12-17 01:12 UTC, shueja commented on docs/usage/saving.md
> +This opens the system’s file select dialog to select the robot’s `.chor` file. This .chor file should be under the folders "src/main/deploy/choreo"
```suggestion
This opens the system’s file select dialog to select the robot’s `.chor` file. This .chor file should be under the folders `src/main/deploy/choreo`
```

2024-12-17 01:12 UTC, shueja commented on docs/usage/saving.md
>  !!! note
Remove this note or change it to something accurate.

2024-12-17 01:12 UTC, shueja commented on docs/usage/saving.md
> +in the same directory(or folder) that your .chor file is stored in.
```suggestion
in the same directory (or folder) that your .chor file is stored in.
```

2024-12-17 01:12 UTC, shueja commented on docs/usage/saving.md
> +the deploy/choreo directory; for python teams, they must be placed in the root directory.
```suggestion
the `deploy/choreo` directory; for Python teams, they must be placed in the root directory.
```

2024-12-17 01:12 UTC, shueja commented on docs/usage/saving.md
> +1. Create a "choreo" folder within the "deploy" folder of your robot project.
```suggestion
1. Create a `choreo` folder within the `deploy` folder of your robot project.
```

2024-12-17 01:12 UTC, shueja commented on docs/usage/saving.md
> +   The deploy folder can be found under "src/main".
```suggestion
   The deploy folder can be found under `src/main`.
```

2024-12-17 01:12 UTC, shueja commented on docs/usage/saving.md
> +3. Navigate to the location of your robot project and find the "src/main/deploy/choreo" folder within it.
```suggestion
3. Navigate to the location of your robot project and find the `src/main/deploy/choreo` folder within it.
```

2024-12-17 05:12 UTC, shueja commented on docs/usage/saving.md
> +Choreo’s file saving mechanism ties into a WPILib robot root directory, wherein a single `.chor` file lives in the project’s root folder.
```suggestion

```

2024-12-17 05:12 UTC, shueja commented on docs/usage/saving.md
>  !!! note
```suggestion

```

2024-12-17 05:14 UTC, shueja approved these changes

2024-12-17 05:43 UTC, merged