Editing paths docs
SleipnirGroup/Choreo pull request #1039
Opened 2024-12-18 06:43 UTC by spacey-sooty

2024-12-19 03:01 UTC, shueja requested changes
Don't use your team's project for these demo videos please.

2024-12-19 19:31 UTC, oh-yes-0-fps commented
> Don't use your team's project for these demo videos please.

Whats the reason for that?

2024-12-19 20:22 UTC, shueja commented
> > Don't use your team's project for these demo videos please.
> 
> Whats the reason for that?

At the very least, don’t include the VeryBadIdeaTm path.

2025-01-02 22:39 UTC, shueja approved these changes

2025-01-06 00:13 UTC, merged