[docs] Document Settings Improvements
SleipnirGroup/Choreo pull request #1068
Opened 2024-12-24 06:33 UTC by DeltaDizzy

Fixes #730

2024-12-24 07:39 UTC, shueja requested changes

2024-12-24 07:39 UTC, shueja commented on src/components/config/robotconfig/TheoreticalPanel.tsx
> +              suffix={`${MetersOrFeet(imp)}/s^2`}
```suggestion
              suffix={`${MetersOrFeet(imp)}/s²`}
```

2024-12-24 07:39 UTC, shueja commented on docs/media/document-settings.png
Not sure we need this pic in addition to the one below: plus it doesn't have the ^2 fix.

2024-12-26 02:38 UTC, oh-yes-0-fps approved these changes

2024-12-26 03:03 UTC, shueja requested changes
Approved

2024-12-26 03:03 UTC, shueja commented on docs/document-settings.md
With a single tab, this page is a bit of a stub, but I think we'll add more tabs for various features again in the future.

2024-12-26 03:03 UTC, shueja commented on docs/document-settings/robot-configuration.md
>  - **Floor Accel** $[m/s^2]$: The maximum acceleration reached by the robot when driving in a straight line and not rotating
```suggestion
- **Floor Accel** $[m/s^2]$: The maximum acceleration reached by the robot when driving in a straight line and not rotating. The minimum of traction and motor limits.
```

2024-12-26 20:06 UTC, shueja submitted a review, later dismissed

2024-12-26 20:06 UTC, shueja commented on docs/document-settings.md
> +See the page below for an explanations of how to use the Document Settings panel.
```suggestion
See the page below for an explanation of how to use the Document Settings panel.
```

2024-12-27 04:15 UTC, merged