Fix headings to wrap optimally before solver
SleipnirGroup/Choreo pull request #204
Opened 2023-12-23 08:48 UTC by shueja

Closes #51

2023-12-27 04:52 UTC, Awesomeplayer165 requested changes
Formatting things but general functionality lgtm

2023-12-27 04:52 UTC, Awesomeplayer165 commented on src/document/HolonomicPathStore.ts
> +              ) {
Consider making the code more consistent

2023-12-29 08:22 UTC, shueja commented
> Formatting things but general functionality lgtm

I tried to fix this and the formatter reverted it. I'm not going to try to fight it to make the line breaks consistent

2023-12-29 08:24 UTC, Awesomeplayer165 commented
no problem

2023-12-29 08:24 UTC, Awesomeplayer165 approved these changes

2023-12-29 08:30 UTC, merged