split at stop points
SleipnirGroup/Choreo pull request #236
Opened 2024-01-09 04:45 UTC by Lewis-Seiden

2024-01-10 21:51 UTC, shueja commented
A thought:
Do we want all stop points to necessarily be split points?

2024-01-12 17:16 UTC, Lewis-Seiden commented
> A thought: Do we want all stop points to necessarily be split points?

i think so? a user can manually add split segments together again afterwards anyways

2024-01-16 18:01 UTC, shueja requested changes
Still missing c++ equivalents on the group loading

2024-01-16 21:25 UTC, calcmogul requested changes

2024-01-16 21:25 UTC, calcmogul commented on choreolib/src/main/native/cpp/choreo/lib/Choreo.cpp
> +  for (auto const& dir_entry : std::filesystem::directory_iterator{sandbox}) {
```suggestion
  for (const auto& dir_entry : std::filesystem::directory_iterator{sandbox}) {
```

2024-01-16 21:25 UTC, calcmogul commented on choreolib/src/main/native/cpp/choreo/lib/Choreo.cpp
> +      segmentCount = 0;
This look is a no-op.

2024-01-16 21:25 UTC, calcmogul commented on choreolib/src/main/native/include/choreo/lib/Choreo.h
> +   * segment does not exist.
```suggestion
   * Loads the split parts of the specified trajectory.
   *
   * ChoreoLib expects split .traj files to be placed in
   * src/main/deploy/choreo/[trajName].[segmentNumber].traj.
   *
   * This method determines the number of parts to load by counting the files
   * that match the pattern "trajName.X.traj", where X is a string of digits.
   * Let this count be N. It then attempts to load "trajName.1.traj" through
   * "trajName.N.traj", consecutively counting up.
   *
   * @param trajName the path name in Choreo. Do not include ".traj" here.
   * @return The array of segments, in order.
   * @throws std::runtime_error If any files cannot be loaded.
```

2024-01-16 21:27 UTC, calcmogul requested changes

2024-01-16 21:30 UTC, calcmogul commented on choreolib/src/main/native/cpp/choreo/lib/Choreo.cpp
> +  for (int i = 1; i <= segmentCount; i++) {
```suggestion
  for (int i = 1; i <= segmentCount; ++i) {
```

2024-01-16 21:30 UTC, calcmogul commented on choreolib/src/main/java/com/choreo/lib/Choreo.java
> +    for (int i = 1; i <= segmentCount; i++) {
```suggestion
    for (int i = 1; i <= segmentCount; ++i) {
```

2024-01-16 21:32 UTC, calcmogul commented on choreolib/src/main/java/com/choreo/lib/Choreo.java
> +    var traj_dir = new File(Filesystem.getDeployDirectory(), "choreo");
This code is pretty messy. Consider adding some blank lines to logically separate different pieces.

2024-01-16 22:55 UTC, calcmogul commented
Actually, this whole vendordep has a lot of documentation issues, including in code outside this PR. Did we ever publish Doxygen/JavaDoc docs for ChoreoLib?

2024-01-16 23:34 UTC, shueja approved these changes

2024-01-16 23:37 UTC, calcmogul approved these changes

2024-01-16 23:50 UTC, merged