Arithmetic support for numerical input fields
SleipnirGroup/Choreo pull request #262
Opened 2024-01-16 06:20 UTC by tandej

Let's try this again...

Simply upstreaming the changes from c9814a5, but git rebase crapped itself the first time :(

2024-01-16 06:22 UTC, jlbabilino commented on package.json
> +    "mathjs": "^11.9.1",
This should be version `12.3.0`

2024-01-16 06:22 UTC, jlbabilino commented on src-tauri/libdummy.so*
> +dummy file (see "scripts/build_utils.cjs")
Don't commit this

2024-01-16 06:27 UTC, jlbabilino commented on src/components/input/Input.tsx
> +            let newNumber = parseFloat(parse(this.state.editedValue).evaluate().toString());
Make sure to run `npm run fixFormat`

2024-01-16 06:28 UTC, shueja requested changes

2024-01-16 06:28 UTC, shueja commented on src/components/input/Input.tsx
> +            let newNumber = parseFloat(parse(this.state.editedValue).evaluate().toString());
If this is parsed as numeric by mathjs we don’t need an extra toString and parseFloat here

2024-01-16 06:42 UTC, jlbabilino commented
Is this a new issue?

https://github.com/SleipnirGroup/Choreo/assets/28580376/fedcb5fa-743e-436b-a3d2-96765ee8aa0b

2024-08-25 19:42 UTC, shueja commented
Superseded by #562

2024-08-25 19:42 UTC, closed without merging