Feature: Path Gradient
SleipnirGroup/Choreo pull request #419
Opened 2024-03-27 07:51 UTC by Awesomeplayer165

A selectable path gradient:
1. None (what we have been using so far)
2. Velocity (default, what's most intuitive)
3. Progress
4. Centripetal
5. Acceleration
6. Dt

<img width="1312" alt="7149" src="https://github.com/SleipnirGroup/Choreo/assets/70717139/ab37692c-3557-429c-868f-7d8f5b311981">

2024-03-29 06:59 UTC, Awesomeplayer165 commented
<img width="1624" alt="image" src="https://github.com/SleipnirGroup/Choreo/assets/70717139/6be3e345-7ae5-4d20-a861-039ae1d6ce0b">

2024-03-30 04:37 UTC, Awesomeplayer165 commented
Added menu.

<img width="288" alt="88059" src="https://github.com/SleipnirGroup/Choreo/assets/70717139/6364ab2b-08e3-4abc-aa7c-810dd2d0898f">

2024-03-30 20:37 UTC, Gold872 commented
I think the gradient colors for velocity should be swapped, it makes more sense to have it be green when it's slower since green is generally an indicator for something being small

2024-03-30 22:22 UTC, shueja commented
> I think the gradient colors for velocity should be swapped, it makes more sense to have it be green when it's slower since green is generally an indicator for something being small
> 
> Having additional gradients for angular velocity/acceleration could also be helpful in some scenarios

Counterpoint: red means slow on GPS apps.

2024-03-31 02:53 UTC, Awesomeplayer165 commented
Changes agreed upon from discord:
adding segments, removing centripetal, and adding a description

2024-03-31 15:53 UTC, shueja commented on src/components/config/robotconfig/PathGradient.tsx
> +    description: "Distance between intervals. Shorter is expressed as green.",
“Shorter time difference between intervals is shown as green”

I would prefer “shown” instead of “expressed” for all of these.

2024-03-31 15:55 UTC, shueja requested changes
One thing about tooltips is all I can find from my phone.

2024-03-31 16:05 UTC, Awesomeplayer165 commented
One thing I found from my phone is the descriptions should be rendered as tooltips.

2024-04-02 16:36 UTC, Awesomeplayer165 commented
Added path segment functionality. made menu and toolbar nicer to interact with.

<img width="1312" alt="18285" src="https://github.com/SleipnirGroup/Choreo/assets/70717139/5c4a6f53-0923-4422-b600-266bd1834e79">

2024-04-02 16:43 UTC, Awesomeplayer165 commented
Make color generation work for any path length by oscilating of i between 0 and 1 scaled by 360. The first segment will always be red since 0 is red on hsl scale

<img width="1312" alt="65898" src="https://github.com/SleipnirGroup/Choreo/assets/70717139/4b998ebc-4900-4bdd-a7d6-4434ec05d802">

2024-04-02 16:46 UTC, shueja approved these changes

2024-04-02 17:00 UTC, Awesomeplayer165 commented
Add angular velocity gradient

<img width="1312" alt="52334" src="https://github.com/SleipnirGroup/Choreo/assets/70717139/5f0eff68-5b38-4796-b0dd-516d04d6fe92">

2024-04-03 01:48 UTC, merged

2024-04-03 01:51 UTC, calcmogul commented on src/components/config/robotconfig/PathGradient.tsx
> +      Math.sin(point.angularVelocity / 0.00000000001) * 40
This seems like a hack.