[choreo] Add differential drivetrain support
SleipnirGroup/Choreo pull request #541
Opened 2024-07-21 08:01 UTC by Superbro525Alt

Resolves #537

2024-07-21 11:49 UTC, spacey-sooty requested changes

2024-07-21 11:49 UTC, spacey-sooty commented on src-tauri/src/main.rs
> +    println!("{:?}", config);
```suggestion
```

2024-07-21 11:49 UTC, spacey-sooty commented on src-tauri/src/main.rs
> +use core::panic;
```suggestion
```
You shouldn't import from core.
Shouldn't be required anyways

2024-07-21 11:49 UTC, spacey-sooty commented on src-tauri/src/main.rs
> +
```suggestion
```

2024-07-21 11:49 UTC, spacey-sooty commented on src-tauri/src/main.rs
> +
```suggestion
```

2024-09-01 20:17 UTC, shueja commented
Superseded by other commits and UI rearchitecture. Thank you for the work though, since this will help us do the UI changes.

2024-09-01 20:17 UTC, closed without merging