[choreo] Rename traj to output
SleipnirGroup/Choreo pull request #597
Opened 2024-08-28 01:52 UTC by spacey-sooty

2024-08-28 03:02 UTC, shueja commented
![91mg26](https://github.com/user-attachments/assets/4c1641e7-6bf5-421b-9263-cb6b04c1d207)
This will need the frontend to match.

2024-08-28 03:07 UTC, spacey-sooty commented
Me forgor search and replace 💀

2024-09-01 17:02 UTC, calcmogul requested changes
With this PR, the generate button does nothing.

2024-09-02 04:59 UTC, closed without merging

2024-09-02 04:59 UTC, calcmogul commented
Superseded by #602.