Upload standalone binaries as artifacts
SleipnirGroup/Choreo pull request #743
Opened 2024-09-21 19:16 UTC by calcmogul

Fixes #742.

2024-09-21 19:55 UTC, calcmogul commented
Main questions I have about this still are whether the standalone binaries work on Windows and macOS, and whether I modified the release workflow correctly.

2024-09-21 23:06 UTC, Gold856 requested changes

2024-09-21 23:06 UTC, Gold856 commented on .github/workflows/choreo.yml
> +        run: zip -r ${{ matrix.artifact-name }}.zip . -i target/x86_64-pc-windows-msvc/release/choreo.exe target/x86_64-pc-windows-msvc/release/choreo-cli.exe target/x86_64-pc-windows-msvc/release/bu
```suggestion
        run: Compress-Archive -DestinationPath ${{ matrix.artifact-name }}.zip . -Path target/x86_64-pc-windows-msvc/release/choreo.exe,target/x86_64-pc-windows-msvc/release/choreo-cli.exe,target/x86_64-pc-windows-msvc/release/bundle/nsis/*.exe
```

2024-09-21 23:06 UTC, Gold856 commented on .github/workflows/choreo.yml
> +        run: zip -r ${{ matrix.artifact-name }}.zip . -i target/aarch64-pc-windows-msvc/release/choreo.exe target/aarch64-pc-windows-msvc/release/choreo-cli.exe target/aarch64-pc-windows-msvc/release
```suggestion
        run: Compress-Archive -DestinationPath ${{ matrix.artifact-name }}.zip . -Path target/aarch64-pc-windows-msvc/release/choreo.exe,target/aarch64-pc-windows-msvc/release/choreo-cli.exe,target/aarch64-pc-windows-msvc/release/bundle/nsis/*.exe
```

2024-09-22 00:26 UTC, Gold856 requested changes

2024-09-22 00:26 UTC, Gold856 commented on .github/workflows/choreo.yml
> +        run: Compress-Archive -DestinationPath ${{ matrix.artifact-name }}.zip . -Path target/x86_64-pc-windows-msvc/release/choreo.exe,target/x86_64-pc-windows-msvc/release/choreo-cli.exe,target/x86
```suggestion
        run: Compress-Archive -DestinationPath ${{ matrix.artifact-name }}.zip -Path target/x86_64-pc-windows-msvc/release/choreo.exe,target/x86_64-pc-windows-msvc/release/choreo-cli.exe,target/x86_64-pc-windows-msvc/release/bundle/nsis/*.exe
```

2024-09-22 00:26 UTC, Gold856 commented on .github/workflows/choreo.yml
> +        run: Compress-Archive -DestinationPath ${{ matrix.artifact-name }}.zip . -Path target/aarch64-pc-windows-msvc/release/choreo.exe,target/aarch64-pc-windows-msvc/release/choreo-cli.exe,target/a
```suggestion
        run: Compress-Archive -DestinationPath ${{ matrix.artifact-name }}.zip -Path target/aarch64-pc-windows-msvc/release/choreo.exe,target/aarch64-pc-windows-msvc/release/choreo-cli.exe,target/aarch64-pc-windows-msvc/release/bundle/nsis/*.exe
```

2024-09-22 01:00 UTC, Gold856 commented
Can confirm Windows x86_64 works.

2024-09-22 19:56 UTC, merged