Toggleable constraints
SleipnirGroup/Choreo pull request #750
Opened 2024-09-22 20:59 UTC by Lewis-Seiden

2024-09-22 21:19 UTC, calcmogul requested changes

2024-09-22 21:19 UTC, calcmogul commented on src/document/path/ChoreoPathStore.ts
> +      console.log("store: ", store);
Should these console logs be removed?

2024-09-22 21:19 UTC, calcmogul commented on src/document/ConstraintDataStore.tsx
> +    // };
Remove this dead code.

2024-09-22 23:47 UTC, shueja approved these changes

2024-09-23 02:12 UTC, calcmogul approved these changes

2024-09-23 02:12 UTC, merged