Event marker refactor
SleipnirGroup/Choreo pull request #773
Opened 2024-09-25 19:21 UTC by shueja

2024-10-06 08:56 UTC, spacey-sooty commented on .vscode/settings.json
> +    "files.associations": {
These should probably be in the user settings.json

2024-10-08 17:37 UTC, shueja commented
C++, Java and Python deserialization changes have been tested. Ready for review.

2024-10-08 18:03 UTC, calcmogul approved these changes
Does the event marker stuff have C++ tests?

2024-10-08 18:43 UTC, calcmogul requested changes
Should add an assert to the Java test while you're at it. The commented out imports in ChoreoTests.java can also be removed.

2024-10-08 22:17 UTC, calcmogul approved these changes

2024-10-08 22:17 UTC, merged