[trajoptlib] Add Python bindings using nanobind
SleipnirGroup/Choreo pull request #848
Opened 2024-10-07 07:16 UTC by spacey-sooty

2024-10-07 15:23 UTC, calcmogul requested changes

2024-10-07 15:23 UTC, calcmogul commented on trajoptlib/py/cpp/BindSwerve.cpp
> +          "mass"_a, "moi"_a, "wheelRadius"_a, "wheelMaxAngularVelocity"_a,
Python APIs should use snake case, not mixed case.

2024-10-07 15:51 UTC, calcmogul requested changes
This needs some tests to ensure the package functions.

2024-10-07 22:53 UTC, calcmogul commented on trajoptlib/pyproject.toml
> +version = "0.0.1.dev124"
This should be changed to how choreolib does its version updates.

2025-05-22 14:36 UTC, spacey-sooty commented
Restarted on another branch.

2025-05-22 14:36 UTC, closed without merging