Update C++ Autonomous Functionality
SleipnirGroup/Choreo pull request #849
Opened 2024-10-07 16:43 UTC by r4stered

This updates the C++ version of the autonomous functionality to compile and be useable. It is different from the Java version because of CommandPtr being move only.  

I still need to add the AutoChooser class, but otherwise I have tested functionality here: https://github.com/r4stered/choreobetarobot

2024-10-08 06:21 UTC, spacey-sooty commented on choreolib/src/main/native/include/choreo/Choreo.h
> +      if (!fileBuffer || ec) {
We'll have to update this for 2025

2024-10-08 06:21 UTC, spacey-sooty commented on choreolib/src/main/native/include/choreo/Choreo.h
> +    if (!fileBuffer || ec) {
ditto

2024-10-09 02:57 UTC, oh-yes-0-fps commented
I'm really not a big fan of how infective the `year` generic is. What is it getting you with it being a generic/template?
99% of users will never use anything other than the latest year. Does cpp support generic defaults?

2024-10-09 07:56 UTC, spacey-sooty commented
C++ supports generic defaults which I think would be a good addition here

2024-10-09 09:59 UTC, spacey-sooty requested changes
Some docs already assumed a default even though we didn't have one

2024-10-09 09:59 UTC, spacey-sooty commented on choreolib/src/main/native/include/choreo/auto/AutoChooser.h
> +template <choreo::TrajectorySample SampleType, int Year>
```suggestion
template <choreo::TrajectorySample SampleType, int Year = 2024>
```

2024-10-09 09:59 UTC, spacey-sooty commented on choreolib/src/main/native/include/choreo/auto/AutoChooser.h
> + * @tparam Year The field year.
```suggestion
 * @tparam Year The field year. Defaults to the current year.
```

2024-10-09 09:59 UTC, spacey-sooty commented on choreolib/src/main/native/include/choreo/auto/AutoLoop.h
> +template <choreo::TrajectorySample SampleType, int Year>
```suggestion
template <choreo::TrajectorySample SampleType, int Year = 2024>
```

2024-10-09 09:59 UTC, spacey-sooty commented on choreolib/src/main/native/include/choreo/auto/AutoTrajectory.h
>  template <choreo::TrajectorySample SampleType, int Year>
```suggestion
template <choreo::TrajectorySample SampleType, int Year = 2024>
```

2024-10-09 09:59 UTC, spacey-sooty commented on choreolib/src/main/native/include/choreo/auto/AutoTrajectory.h
>  template <choreo::TrajectorySample SampleType, int Year>
Doc comment above needs update

2024-10-09 13:32 UTC, r4stered commented
> C++ supports generic defaults which I think would be a good addition here

There is now a default param to the current year using the util class.

2024-10-09 13:36 UTC, spacey-sooty submitted a review, later dismissed

2024-10-09 13:36 UTC, spacey-sooty commented on choreolib/src/main/native/include/choreo/auto/AutoTrajectory.h
>   * @tparam Year The field year.
```suggestion
 * @tparam Year The field year. Defaults to the current year.
```

2024-10-09 13:37 UTC, spacey-sooty commented
@r4stered docs still need updates

2024-10-12 13:50 UTC, spacey-sooty approved these changes

2024-10-14 22:07 UTC, calcmogul approved these changes

2024-10-14 22:07 UTC, merged