Fixed `done` trigger method
SleipnirGroup/Choreo pull request #881
Opened 2024-10-19 04:05 UTC by oh-yes-0-fps

Renamed `AutoLoop` to `AutoRoutine`
Fixed `auto-routines` doc examples after removal of `TriggerExt`

2024-10-19 04:10 UTC, calcmogul commented
Needs a C++ port.

2024-10-19 04:31 UTC, oh-yes-0-fps commented
Cpp would likely just store a `std::string_view` in the routine to do trajectory equality with most recent run in routine.

2024-10-19 05:10 UTC, calcmogul commented
std::string_view isn't an owning container, so it shouldn't be used as a member variable.

2024-10-20 09:05 UTC, spacey-sooty commented
Can you split AutoLoop -> AutoRoutine to a seperate PR?

2024-10-22 00:31 UTC, spacey-sooty requested changes

2024-10-22 00:31 UTC, spacey-sooty commented on choreolib/src/main/java/choreo/auto/AutoTrajectory.java
> +    return false;
This can be simplified I believe

2024-10-25 14:51 UTC, spacey-sooty approved these changes

2024-10-25 15:04 UTC, merged