fixed `done` logic
SleipnirGroup/Choreo pull request #884
Opened 2024-10-21 21:23 UTC by oh-yes-0-fps

`done` is extensively document in its specific behavior and why it is the way it is.

The commit history looks weird here when un-squashed, this is built off of #881 with just reverting the commit in that where the change to `done` logic was reverted.
I'm sure there was a better way but idk how to do it

2024-10-25 15:05 UTC, spacey-sooty submitted a review, later dismissed
Rebase

2024-10-26 02:48 UTC, spacey-sooty requested changes
I'd like a test to make sure this behaviour doesn't break

2024-10-26 04:34 UTC, oh-yes-0-fps commented
I ran it in sim in my robot project and there were no regressions. I will be running in actual matches in abt 8 hrs

2024-10-26 05:53 UTC, spacey-sooty commented
I mean like a unit test

2024-10-26 14:57 UTC, spacey-sooty commented on choreolib/src/main/java/choreo/auto/AutoFactory.java
> +        }
Can you add a comment to explain this?

2024-10-31 06:07 UTC, spacey-sooty approved these changes

2024-10-31 06:16 UTC, merged